#language: en
Feature: Sugerir Pensum
	In order to optimizar la asignacion de cupos
	I want to determinar los conflictos de horario

	Scenario: Sugerir Pensum 4 semestres
	Given I am on "/estudiantes/"
	And I click link "New Estudiante"	
	And I fill in "estudiante_nombre" with "Estudiante prueba 1"
	And I fill in "estudiante_email" with "a@a.a"
	And I fill in "estudiante_semestre_actual" with "1"
	And I fill in "estudiante_password" with "123456"
	And I fill in "estudiante_password_confirmation" with "123456"
	And I click button "Crear Estudiante"
	And I am on "/estudiantes/seleccionar"
	When I select "Estudiante prueba 1" in "estudiante_id"
	And I click button "Seleccionar estudiante"
	And I click link "Agregar materia"
	Then I should see "Curso prueba 1"
	And I should see "201410"
	And I should see "Curso prueba 2"	
	And I should see "201420"
	And I should see "Curso prueba 3"	
	And I should see "201510"
	And I should see "Curso prueba 4"	
	And I should see "201520"

	Scenario: Sugerir Pensum 3 semestres
	Given I am on "/estudiantes/"
	And I click link "New Estudiante"	
	And I fill in "estudiante_nombre" with "Estudiante prueba 2"
	And I fill in "estudiante_email" with "a@a.a"
	And I fill in "estudiante_semestre_actual" with "2"
	And I fill in "estudiante_password" with "123456"
	And I fill in "estudiante_password_confirmation" with "123456"
	And I click button "Crear Estudiante"
	And I am on "/estudiantes/seleccionar"
	When I select "Estudiante prueba 2" in "estudiante_id"
	And I click button "Seleccionar estudiante"
	And I click link "Agregar materia"
	And I should see "Curso prueba 2"	
	And I should see "201410"
	And I should see "Curso prueba 3"	
	And I should see "201420"
	And I should see "Curso prueba 4"	
	And I should see "201510"

	Scenario: Sugerir Pensum 2 semestres
	Given I am on "/estudiantes/"
	And I click link "New Estudiante"	
	And I fill in "estudiante_nombre" with "Estudiante prueba 3"
	And I fill in "estudiante_email" with "a@a.a"
	And I fill in "estudiante_semestre_actual" with "3"
	And I fill in "estudiante_password" with "123456"
	And I fill in "estudiante_password_confirmation" with "123456"
	And I click button "Crear Estudiante"
	And I am on "/estudiantes/seleccionar"
	When I select "Estudiante prueba 3" in "estudiante_id"
	And I click button "Seleccionar estudiante"
	And I click link "Agregar materia"
	And I should see "Curso prueba 3"	
	And I should see "201410"
	And I should see "Curso prueba 4"	
	And I should see "201420"

	Scenario: Sugerir Pensum 1 semestre	
	Given I am on "/estudiantes/"
	And I click link "New Estudiante"	
	And I fill in "estudiante_nombre" with "Estudiante prueba 4"
	And I fill in "estudiante_email" with "a@a.a"
	And I fill in "estudiante_semestre_actual" with "4"
	And I fill in "estudiante_password" with "123456"
	And I fill in "estudiante_password_confirmation" with "123456"
	And I click button "Crear Estudiante"
	And I am on "/estudiantes/seleccionar"
	Given I am on "/estudiantes/seleccionar"
	When I select "Estudiante prueba 4" in "estudiante_id"
	And I click button "Seleccionar estudiante"
	And I click link "Agregar materia"
	And I should see "Curso prueba 4"	
	And I should see "201410"