require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfertaController do

  # This should return the minimal set of attributes required to create a valid
  # Ofertum. As you add validations to Ofertum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cupos" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OfertaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all oferta as @oferta" do
      ofertum = Ofertum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:oferta).should eq([ofertum])
    end
  end

  describe "GET show" do
    it "assigns the requested ofertum as @ofertum" do
      ofertum = Ofertum.create! valid_attributes
      get :show, {:id => ofertum.to_param}, valid_session
      assigns(:ofertum).should eq(ofertum)
    end
  end

  describe "GET new" do
    it "assigns a new ofertum as @ofertum" do
      get :new, {}, valid_session
      assigns(:ofertum).should be_a_new(Ofertum)
    end
  end

  describe "GET edit" do
    it "assigns the requested ofertum as @ofertum" do
      ofertum = Ofertum.create! valid_attributes
      get :edit, {:id => ofertum.to_param}, valid_session
      assigns(:ofertum).should eq(ofertum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ofertum" do
        expect {
          post :create, {:ofertum => valid_attributes}, valid_session
        }.to change(Ofertum, :count).by(1)
      end

      it "assigns a newly created ofertum as @ofertum" do
        post :create, {:ofertum => valid_attributes}, valid_session
        assigns(:ofertum).should be_a(Ofertum)
        assigns(:ofertum).should be_persisted
      end

      it "redirects to the created ofertum" do
        post :create, {:ofertum => valid_attributes}, valid_session
        response.should redirect_to(Ofertum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ofertum as @ofertum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ofertum.any_instance.stub(:save).and_return(false)
        post :create, {:ofertum => { "cupos" => "invalid value" }}, valid_session
        assigns(:ofertum).should be_a_new(Ofertum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ofertum.any_instance.stub(:save).and_return(false)
        post :create, {:ofertum => { "cupos" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ofertum" do
        ofertum = Ofertum.create! valid_attributes
        # Assuming there are no other oferta in the database, this
        # specifies that the Ofertum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ofertum.any_instance.should_receive(:update).with({ "cupos" => "1" })
        put :update, {:id => ofertum.to_param, :ofertum => { "cupos" => "1" }}, valid_session
      end

      it "assigns the requested ofertum as @ofertum" do
        ofertum = Ofertum.create! valid_attributes
        put :update, {:id => ofertum.to_param, :ofertum => valid_attributes}, valid_session
        assigns(:ofertum).should eq(ofertum)
      end

      it "redirects to the ofertum" do
        ofertum = Ofertum.create! valid_attributes
        put :update, {:id => ofertum.to_param, :ofertum => valid_attributes}, valid_session
        response.should redirect_to(ofertum)
      end
    end

    describe "with invalid params" do
      it "assigns the ofertum as @ofertum" do
        ofertum = Ofertum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ofertum.any_instance.stub(:save).and_return(false)
        put :update, {:id => ofertum.to_param, :ofertum => { "cupos" => "invalid value" }}, valid_session
        assigns(:ofertum).should eq(ofertum)
      end

      it "re-renders the 'edit' template" do
        ofertum = Ofertum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ofertum.any_instance.stub(:save).and_return(false)
        put :update, {:id => ofertum.to_param, :ofertum => { "cupos" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ofertum" do
      ofertum = Ofertum.create! valid_attributes
      expect {
        delete :destroy, {:id => ofertum.to_param}, valid_session
      }.to change(Ofertum, :count).by(-1)
    end

    it "redirects to the oferta list" do
      ofertum = Ofertum.create! valid_attributes
      delete :destroy, {:id => ofertum.to_param}, valid_session
      response.should redirect_to(oferta_url)
    end
  end

end
