require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PensumsController do

  # This should return the minimal set of attributes required to create a valid
  # Pensum. As you add validations to Pensum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PensumsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pensums as @pensums" do
      pensum = Pensum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pensums).should eq([pensum])
    end
  end

  describe "GET show" do
    it "assigns the requested pensum as @pensum" do
      pensum = Pensum.create! valid_attributes
      get :show, {:id => pensum.to_param}, valid_session
      assigns(:pensum).should eq(pensum)
    end
  end

  describe "GET new" do
    it "assigns a new pensum as @pensum" do
      get :new, {}, valid_session
      assigns(:pensum).should be_a_new(Pensum)
    end
  end

  describe "GET edit" do
    it "assigns the requested pensum as @pensum" do
      pensum = Pensum.create! valid_attributes
      get :edit, {:id => pensum.to_param}, valid_session
      assigns(:pensum).should eq(pensum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pensum" do
        expect {
          post :create, {:pensum => valid_attributes}, valid_session
        }.to change(Pensum, :count).by(1)
      end

      it "assigns a newly created pensum as @pensum" do
        post :create, {:pensum => valid_attributes}, valid_session
        assigns(:pensum).should be_a(Pensum)
        assigns(:pensum).should be_persisted
      end

      it "redirects to the created pensum" do
        post :create, {:pensum => valid_attributes}, valid_session
        response.should redirect_to(Pensum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pensum as @pensum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pensum.any_instance.stub(:save).and_return(false)
        post :create, {:pensum => {  }}, valid_session
        assigns(:pensum).should be_a_new(Pensum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pensum.any_instance.stub(:save).and_return(false)
        post :create, {:pensum => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pensum" do
        pensum = Pensum.create! valid_attributes
        # Assuming there are no other pensums in the database, this
        # specifies that the Pensum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pensum.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => pensum.to_param, :pensum => { "these" => "params" }}, valid_session
      end

      it "assigns the requested pensum as @pensum" do
        pensum = Pensum.create! valid_attributes
        put :update, {:id => pensum.to_param, :pensum => valid_attributes}, valid_session
        assigns(:pensum).should eq(pensum)
      end

      it "redirects to the pensum" do
        pensum = Pensum.create! valid_attributes
        put :update, {:id => pensum.to_param, :pensum => valid_attributes}, valid_session
        response.should redirect_to(pensum)
      end
    end

    describe "with invalid params" do
      it "assigns the pensum as @pensum" do
        pensum = Pensum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pensum.any_instance.stub(:save).and_return(false)
        put :update, {:id => pensum.to_param, :pensum => {  }}, valid_session
        assigns(:pensum).should eq(pensum)
      end

      it "re-renders the 'edit' template" do
        pensum = Pensum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pensum.any_instance.stub(:save).and_return(false)
        put :update, {:id => pensum.to_param, :pensum => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pensum" do
      pensum = Pensum.create! valid_attributes
      expect {
        delete :destroy, {:id => pensum.to_param}, valid_session
      }.to change(Pensum, :count).by(-1)
    end

    it "redirects to the pensums list" do
      pensum = Pensum.create! valid_attributes
      delete :destroy, {:id => pensum.to_param}, valid_session
      response.should redirect_to(pensums_url)
    end
  end

end
