require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PropuestaController do

  # This should return the minimal set of attributes required to create a valid
  # Propuestum. As you add validations to Propuestum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PropuestaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all propuesta as @propuesta" do
      propuestum = Propuestum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:propuesta).should eq([propuestum])
    end
  end

  describe "GET show" do
    it "assigns the requested propuestum as @propuestum" do
      propuestum = Propuestum.create! valid_attributes
      get :show, {:id => propuestum.to_param}, valid_session
      assigns(:propuestum).should eq(propuestum)
    end
  end

  describe "GET new" do
    it "assigns a new propuestum as @propuestum" do
      get :new, {}, valid_session
      assigns(:propuestum).should be_a_new(Propuestum)
    end
  end

  describe "GET edit" do
    it "assigns the requested propuestum as @propuestum" do
      propuestum = Propuestum.create! valid_attributes
      get :edit, {:id => propuestum.to_param}, valid_session
      assigns(:propuestum).should eq(propuestum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Propuestum" do
        expect {
          post :create, {:propuestum => valid_attributes}, valid_session
        }.to change(Propuestum, :count).by(1)
      end

      it "assigns a newly created propuestum as @propuestum" do
        post :create, {:propuestum => valid_attributes}, valid_session
        assigns(:propuestum).should be_a(Propuestum)
        assigns(:propuestum).should be_persisted
      end

      it "redirects to the created propuestum" do
        post :create, {:propuestum => valid_attributes}, valid_session
        response.should redirect_to(Propuestum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved propuestum as @propuestum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Propuestum.any_instance.stub(:save).and_return(false)
        post :create, {:propuestum => {  }}, valid_session
        assigns(:propuestum).should be_a_new(Propuestum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Propuestum.any_instance.stub(:save).and_return(false)
        post :create, {:propuestum => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested propuestum" do
        propuestum = Propuestum.create! valid_attributes
        # Assuming there are no other propuesta in the database, this
        # specifies that the Propuestum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Propuestum.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => propuestum.to_param, :propuestum => { "these" => "params" }}, valid_session
      end

      it "assigns the requested propuestum as @propuestum" do
        propuestum = Propuestum.create! valid_attributes
        put :update, {:id => propuestum.to_param, :propuestum => valid_attributes}, valid_session
        assigns(:propuestum).should eq(propuestum)
      end

      it "redirects to the propuestum" do
        propuestum = Propuestum.create! valid_attributes
        put :update, {:id => propuestum.to_param, :propuestum => valid_attributes}, valid_session
        response.should redirect_to(propuestum)
      end
    end

    describe "with invalid params" do
      it "assigns the propuestum as @propuestum" do
        propuestum = Propuestum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Propuestum.any_instance.stub(:save).and_return(false)
        put :update, {:id => propuestum.to_param, :propuestum => {  }}, valid_session
        assigns(:propuestum).should eq(propuestum)
      end

      it "re-renders the 'edit' template" do
        propuestum = Propuestum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Propuestum.any_instance.stub(:save).and_return(false)
        put :update, {:id => propuestum.to_param, :propuestum => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested propuestum" do
      propuestum = Propuestum.create! valid_attributes
      expect {
        delete :destroy, {:id => propuestum.to_param}, valid_session
      }.to change(Propuestum, :count).by(-1)
    end

    it "redirects to the propuesta list" do
      propuestum = Propuestum.create! valid_attributes
      delete :destroy, {:id => propuestum.to_param}, valid_session
      response.should redirect_to(propuesta_url)
    end
  end

end
